#!/usr/bin/env python3
"""Generate an independent Cargo crate for every pipeline.

Walks assets/pipelines/<category>/<folder>/main.rs, scans imports for
dependencies, writes a Cargo.toml per pipeline (regenerable — never
hand-maintained), then triages:

  - compiles  -> ready (independent workspace root)
  - broken    -> listed in tools/PIPELINE_TRIAGE.md (fix queue, excluded
                 from the workspace so `--workspace` runs stay green)

Usage: python3 tools/gen_pipeline_crates.py [--check-only]
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIPELINES = ROOT / "assets" / "pipelines"
TRIAGE = ROOT / "tools" / "PIPELINE_TRIAGE.md"
CARGO = ROOT / "Cargo.toml"

# crate-used-in-code -> dependency spec
DEP_TABLE = {
    "serde": 'serde = { version = "1.0", features = ["derive"] }',
    "serde_json": 'serde_json = "1.0"',
    "tokio": 'tokio = { version = "1.35", features = ["full"] }',
    "chrono": 'chrono = { version = "0.4", features = ["serde"] }',
    "tracing": 'tracing = "0.1"',
    "tracing_subscriber": 'tracing-subscriber = { version = "0.3", features = ["env-filter"] }',
    "async_trait": 'async-trait = "0.1.81"',
    "lazy_static": 'lazy_static = "1.4"',
    "regex": 'regex = "1.10"',
    "uuid": 'uuid = { version = "1.6", features = ["v4", "serde"] }',
    "reqwest": 'reqwest = { version = "0.11", features = ["json"] }',
    "base64": 'base64 = "0.21"',
    "rand": 'rand = "0.8"',
    "blake3": 'blake3 = "1.5"',
    "hex": 'hex = "0.4"',
}

HEADER = (
    "# Generated by tools/gen_pipeline_crates.py — regenerable, do not hand-edit.\n"
    "# Independent pipeline unit: own build, own tests, connects to the host\n"
    "# and registers itself (see src/pipeline/remote.rs on the host side).\n"
)

TEMPLATE = (
    HEADER
    + '[package]\nname = "ozone-pipeline-{name}"\nversion = "0.4.0"\nedition = "2021"\n\n'
    + "[[bin]]\nname = \"{bin}\"\npath = \"main.rs\"\n\n[dependencies]\n{deps}\n"
    + "\n# Own workspace root: independent unit — builds anywhere, connects over the wire.\n[workspace]\n"
)



def wire_serve_module(main_rs: Path) -> None:
    """Ensure the shared serve module is declared (idempotent).

    Injects only the `#[path]` mod declaration — wiring the serve branch into
    main() is a per-pipeline step done when that pipeline is touched (see the
    text pipeline for the reference implementation).
    """
    src = main_rs.read_text(errors="replace")
    if "mod ozone_serve" in src:
        return
    declaration = (
        '#[path = "../../shared/ozone_serve.rs"]\n'
        "mod ozone_serve;\n\n"
    )
    # Insert after the last top-of-file use statement (or at the top if none).
    lines = src.split("\n")
    last_use = -1
    for i, line in enumerate(lines[:200]):
        if line.startswith("use "):
            last_use = i
    if last_use >= 0:
        lines.insert(last_use + 1, "\n" + declaration.rstrip("\n"))
    else:
        lines.insert(0, declaration)
    main_rs.write_text("\n".join(lines))


def discover() -> list[Path]:
    return sorted(
        p for p in PIPELINES.glob("*/*/main.rs") if p.parent not in (PIPELINES,)
    )


def scan_deps(main_rs: Path) -> tuple[set[str], list[str]]:
    src = main_rs.read_text(errors="replace")
    # ALL path roots (use statements, attributes like #[async_trait::...],
    # fully-qualified macros like tracing::warn!) — not just use statements.
    used = set(re.findall(r"(\w+)::", src))
    # Attribute/macro forms without a path: #[async_trait], lazy_static! {}
    if re.search(r"#\[async_trait\]", src):
        used.add("async_trait")
    if re.search(r"\blazy_static\s*!", src):
        used.add("lazy_static")
    deps, unknown = [], []
    for crate in sorted(used):
        if crate in ("crate", "std", "core", "alloc", "super", "self"):
            continue
        if crate in DEP_TABLE:
            deps.append(DEP_TABLE[crate])
        else:
            unknown.append(crate)
    return deps, unknown


def toml_for(folder: str, deps: list[str]) -> str:
    return TEMPLATE.format(name=folder, bin=folder, deps="\n".join(deps) or "# (none)")


def main() -> int:
    check_only = "--check-only" in sys.argv
    mains = discover()
    print(f"Discovered {len(mains)} pipelines")

    passing, failing = [], []

    for main_rs in mains:
        folder = main_rs.parent.name
        deps, unknown = scan_deps(main_rs)
        cargo_toml = main_rs.parent / "Cargo.toml"

        if not check_only:
            cargo_toml.write_text(toml_for(folder, deps))
            wire_serve_module(main_rs)

        pkg = f"ozone-pipeline-{folder}"
        # Standalone check via --manifest-path (works pre-membership);
        # CARGO_TARGET_DIR pinned to the root so no per-crate target/ dirs.
        import os
        env = dict(os.environ, CARGO_TARGET_DIR=str(ROOT / "target"))
        result = subprocess.run(
            ["cargo", "check", "-q", "--manifest-path", str(cargo_toml)],
            capture_output=True, text=True, cwd=ROOT, timeout=240, env=env,
        )
        status = "PASS" if result.returncode == 0 else "FAIL"
        (passing if result.returncode == 0 else failing).append(
            (folder, pkg, "; ".join(unknown) or "-")
        )
        print(f"  [{status}] {folder}  (unknown crates: {'; '.join(unknown) or '-'})")

    # NOTE: pipelines intentionally NOT root members — each is its own
    # workspace root (independence by construction; see header comment).

    TRIAGE.parent.mkdir(exist_ok=True)
    lines = ["# Pipeline crate triage", "", f"Passing: {len(passing)} | Failing: {len(failing)}", ""]
    if failing:
        lines += ["## Broken (excluded from workspace until fixed)", "", "| pipeline | unknown crates |", "|---|---|"]
        lines += [f"| {f} | {u} |" for f, _, u in failing]
    TRIAGE.write_text("\n".join(lines) + "\n")
    print(f"\n{len(passing)} passing, {len(failing)} failing -> {TRIAGE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
