//! Bootstrap module - First-run initialization
//!
//! Copies built-in assets (pipelines, methodologies, blueprints) to data directory.
//! Index files are pre-built and copied, not generated by scanning.
//!
//! All reserved container ID constants live in `crate::types::container`.
//! This module imports them from there — do NOT re-define them here.

use crate::config::OzoneConfig;
use crate::types::container::{
    // ── Types ─────────────────────────────────────────────────────────────────
    Container,
    ContainerType,
    Context,
    GlobalState,
    LocalState,
    Metadata,
    Modality,
    StoragePointers,
    BLUEPRINT_ROOT_ID,
    // ── Runtime graph roots ───────────────────────────────────────────────────
    CHUNK_GRAPH_ROOT_ID,
    CONSCIOUSNESS_COLLECTIVE_ROOT_ID,

    CONSCIOUSNESS_CORE_MEMORY_ROOT_ID,
    CONSCIOUSNESS_EMOTIONAL_ROOT_ID,
    CONSCIOUSNESS_ETHICS_ROOT_ID,
    // ── Consciousness sphere roots ────────────────────────────────────────────
    CONSCIOUSNESS_EXPERIENCE_ROOT_ID,
    CONSCIOUSNESS_IDENTITY_ROOT_ID,
    CONSCIOUSNESS_METACOGNITION_ROOT_ID,
    CONSCIOUSNESS_NARRATIVES_ROOT_ID,
    CONSCIOUSNESS_RELATIONSHIPS_ROOT_ID,
    CONSCIOUSNESS_ROOT_ID,
    CROSS_MODAL_INDEX_ROOT_ID,

    // ── External roots ────────────────────────────────────────────────────────
    EXTERNAL_PACKAGES_ROOT_ID,
    EXTERNAL_ROOT_ID,

    EXTERNAL_URLS_ROOT_ID,

    FILE_GRAPH_ROOT_ID,
    METHODOLOGY_ROOT_ID,
    // ── Extended modality nodes ───────────────────────────────────────────────
    MODALITY_3D_ID,
    MODALITY_AUDIO_ID,
    MODALITY_BCI_ID,
    MODALITY_BIOLOGY_ID,
    MODALITY_CHEMISTRY_ID,
    MODALITY_CODE_ID,
    MODALITY_CONTROL_SYSTEMS_ID,
    MODALITY_DEPTH_ID,
    MODALITY_DNA_ID,
    MODALITY_EEG_ID,

    MODALITY_ELECTROMAGNETIC_ID,
    MODALITY_GEOSPATIAL_ID,
    MODALITY_HAPTIC_ID,
    MODALITY_HYPERSPECTRAL_ID,

    MODALITY_IMAGE_ID,
    MODALITY_IMU_ID,
    MODALITY_KINEMATICS_ID,
    MODALITY_MATH_ID,
    MODALITY_NETWORK_TOPOLOGY_ID,
    MODALITY_PARAMETRIC_CAD_ID,
    MODALITY_PROTEOMICS_ID,
    MODALITY_RADAR_ID,
    MODALITY_ROOT_ID,
    MODALITY_SONAR_ID,
    MODALITY_SOUND_ID,
    // ── Core modality nodes ───────────────────────────────────────────────────
    MODALITY_TEXT_ID,
    MODALITY_THERMAL_ID,
    MODALITY_VIDEO_ID,
    PIPELINE_ROOT_ID,
    // ── System roots ──────────────────────────────────────────────────────────
    ROOT_CONTAINER_ID,
};
use crate::types::{OzoneError, OzoneResult};
use std::fs;
use std::path::{Path, PathBuf};

/// Bootstrap manager for first-run setup
pub struct BootstrapManager {
    config: OzoneConfig,
    data_dir: PathBuf,
    assets_dir: PathBuf,
}

impl BootstrapManager {
    /// Create new bootstrap manager
    pub fn new(config: &OzoneConfig) -> Self {
        Self {
            config: config.clone(),
            data_dir: PathBuf::from(&config.general.data_dir),
            assets_dir: Self::resolve_assets_dir(),
        }
    }

    /// Resolve the assets directory with fallback chain:
    /// 1. OZONE_ASSETS_PATH env var
    /// 2. <binary_dir>/../../assets  (dev: target/release → project root)
    /// 3. <binary_dir>/assets         (production bundle)
    /// 4. ./assets                    (last resort)
    fn resolve_assets_dir() -> PathBuf {
        if let Ok(path) = std::env::var("OZONE_ASSETS_PATH") {
            let p = PathBuf::from(path);
            if p.exists() {
                return p;
            }
        }

        if let Ok(exe) = std::env::current_exe() {
            if let Some(binary_dir) = exe.parent() {
                // Dev layout: target/release/ozone-studio → go up 2 to project root
                if let Some(project_root) = binary_dir.parent().and_then(|p| p.parent()) {
                    let candidate = project_root.join("assets");
                    if candidate.exists() {
                        tracing::info!(path = ?candidate, "Resolved assets dir (dev layout)");
                        return candidate;
                    }
                }
                // Production bundle layout: assets/ next to binary
                let candidate = binary_dir.join("assets");
                if candidate.exists() {
                    tracing::info!(path = ?candidate, "Resolved assets dir (production layout)");
                    return candidate;
                }
            }
        }

        tracing::warn!("Could not resolve assets dir, falling back to ./assets");
        PathBuf::from("assets")
    }

    /// Run bootstrap process
    pub fn run(&self) -> OzoneResult<()> {
        tracing::info!("Running first-time bootstrap...");

        // 1. Create directory structure
        self.create_directories()?;

        // 2. Create Consciousness Spheres Directories
        self.create_consciousness_directories()?;

        // 3. Copy pipeline index and built-in pipelines
        self.copy_pipelines()?;

        // 4. Copy methodology index and built-in methodologies
        self.copy_methodologies()?;

        // 5. Copy blueprint index and built-in blueprints
        self.copy_blueprints()?;

        // 6. Initialize root containers in ZSEI
        self.create_zsei_root_containers()?;

        tracing::info!("Bootstrap complete!");
        Ok(())
    }

    /// Create required directories
    fn create_directories(&self) -> OzoneResult<()> {
        let dirs = [
            self.data_dir.join("pipelines"),
            self.data_dir.join("methodologies"),
            self.data_dir.join("blueprints"),
            self.data_dir.join("local"),
            self.data_dir.join("global"),
            self.data_dir.join("cache"),
            self.data_dir.join("tasks"),
            self.data_dir.join("consciousness"),
            self.data_dir.join("workspaces"),
            self.data_dir.join("graphs"),       // modality graphs
            self.data_dir.join("chunk_graphs"), // persistent chunk graphs
            self.data_dir.join("file_graphs"),  // per-file graphs
            self.data_dir.join("cross_modal"),  // cross-modal index
        ];

        for dir in &dirs {
            fs::create_dir_all(dir).map_err(|e| {
                OzoneError::StorageError(format!("Failed to create {}: {}", dir.display(), e))
            })?;
            tracing::debug!("Created directory: {}", dir.display());
        }

        Ok(())
    }

    fn create_consciousness_directories(&self) -> OzoneResult<()> {
        let consciousness_dir = self.data_dir.join("consciousness");
        fs::create_dir_all(&consciousness_dir)?;

        let spheres = [
            "ExperienceMemory",
            "CoreMemories",
            "EmotionalContext",
            "Identity",
            "Metacognition",
            "Relationships",
            "Ethics",
            "Narratives",
            "Collective",
        ];

        for sphere in spheres {
            fs::create_dir_all(consciousness_dir.join(sphere)).map_err(|e| {
                OzoneError::StorageError(format!(
                    "Failed to create consciousness/{}: {}",
                    sphere, e
                ))
            })?;
        }

        tracing::info!("Initialized consciousness directory structure");
        Ok(())
    }

    fn copy_pipelines(&self) -> OzoneResult<()> {
        let src = self.assets_dir.join("pipelines");
        let dst = self.data_dir.join("pipelines");
        self.copy_dir_recursive(&src, &dst, "pipelines")
    }

    fn copy_methodologies(&self) -> OzoneResult<()> {
        let src = self.assets_dir.join("methodologies");
        let dst = self.data_dir.join("methodologies");
        self.copy_dir_recursive(&src, &dst, "methodologies")
    }

    fn copy_blueprints(&self) -> OzoneResult<()> {
        let src = self.assets_dir.join("blueprints");
        let dst = self.data_dir.join("blueprints");
        self.copy_dir_recursive(&src, &dst, "blueprints")
    }

    /// Recursive copy helper (idempotent, logs what it does)
    fn copy_dir_recursive(&self, src: &Path, dst: &Path, name: &str) -> OzoneResult<()> {
        if !src.exists() {
            tracing::warn!("No {} assets found at {}", name, src.display());
            return Ok(());
        }

        fs::create_dir_all(dst).map_err(|e| {
            OzoneError::StorageError(format!("Failed to create {}: {}", dst.display(), e))
        })?;

        for entry in fs::read_dir(src)? {
            let entry = entry?;
            let src_path = entry.path();
            let dst_path = dst.join(entry.file_name());

            if entry.file_type()?.is_dir() {
                self.copy_dir_recursive(&src_path, &dst_path, name)?;
            } else {
                fs::copy(&src_path, &dst_path).map_err(|e| {
                    OzoneError::StorageError(format!(
                        "Failed to copy {}: {}",
                        src_path.display(),
                        e
                    ))
                })?;
            }
        }

        tracing::info!(
            "Copied full {} structure (including UI components) → {}",
            name,
            dst.display()
        );
        Ok(())
    }

    /// Create all structural root containers in ZSEI local storage.
    ///
    /// Each container is written as a JSON file to `local/<id>.json`.
    /// Existing files are never overwritten (idempotent).
    fn create_zsei_root_containers(&self) -> OzoneResult<()> {
        // (id, name, materialized_path, ContainerType)
        let containers: &[(u64, &str, &str, ContainerType)] = &[
            // System roots
            (ROOT_CONTAINER_ID, "Root", "/", ContainerType::Root),
            (
                MODALITY_ROOT_ID,
                "Modality",
                "/Modality",
                ContainerType::ModalityRoot,
            ),
            (
                METHODOLOGY_ROOT_ID,
                "Methodologies",
                "/Methodologies",
                ContainerType::MethodologyRoot,
            ),
            (
                BLUEPRINT_ROOT_ID,
                "Blueprints",
                "/Blueprints",
                ContainerType::BlueprintRoot,
            ),
            (
                PIPELINE_ROOT_ID,
                "Pipelines",
                "/Pipelines",
                ContainerType::PipelineRoot,
            ),
            (
                CONSCIOUSNESS_ROOT_ID,
                "Consciousness",
                "/Consciousness",
                ContainerType::ConsciousnessRoot,
            ),
            (
                EXTERNAL_ROOT_ID,
                "External",
                "/External",
                ContainerType::ExternalRoot,
            ),
            // Core modality nodes
            (
                MODALITY_TEXT_ID,
                "Text",
                "/Modality/Text",
                ContainerType::Modality,
            ),
            (
                MODALITY_CODE_ID,
                "Code",
                "/Modality/Code",
                ContainerType::Modality,
            ),
            (
                MODALITY_IMAGE_ID,
                "Image",
                "/Modality/Image",
                ContainerType::Modality,
            ),
            (
                MODALITY_AUDIO_ID,
                "Audio",
                "/Modality/Audio",
                ContainerType::Modality,
            ),
            (
                MODALITY_VIDEO_ID,
                "Video",
                "/Modality/Video",
                ContainerType::Modality,
            ),
            (
                MODALITY_MATH_ID,
                "Math",
                "/Modality/Math",
                ContainerType::Modality,
            ),
            (
                MODALITY_CHEMISTRY_ID,
                "Chemistry",
                "/Modality/Chemistry",
                ContainerType::Modality,
            ),
            (
                MODALITY_DNA_ID,
                "DNA",
                "/Modality/DNA",
                ContainerType::Modality,
            ),
            (
                MODALITY_EEG_ID,
                "EEG",
                "/Modality/EEG",
                ContainerType::Modality,
            ),
            // Extended modality nodes (v2 engine pipelines)
            (
                MODALITY_3D_ID,
                "3D",
                "/Modality/3D",
                ContainerType::ThreeDRoot,
            ),
            (
                MODALITY_SOUND_ID,
                "Sound",
                "/Modality/Sound",
                ContainerType::SoundReconstructionRoot,
            ),
            (
                MODALITY_BIOLOGY_ID,
                "Biology",
                "/Modality/Biology",
                ContainerType::BiologyRoot,
            ),
            (
                MODALITY_PROTEOMICS_ID,
                "Proteomics",
                "/Modality/Proteomics",
                ContainerType::ProteomicsRoot,
            ),
            (
                MODALITY_HAPTIC_ID,
                "Haptic",
                "/Modality/Haptic",
                ContainerType::HapticRoot,
            ),
            (
                MODALITY_THERMAL_ID,
                "Thermal",
                "/Modality/Thermal",
                ContainerType::ThermalRoot,
            ),
            (
                MODALITY_DEPTH_ID,
                "Depth",
                "/Modality/Depth",
                ContainerType::DepthRoot,
            ),
            (
                MODALITY_IMU_ID,
                "IMU",
                "/Modality/IMU",
                ContainerType::IMURoot,
            ),
            (
                MODALITY_GEOSPATIAL_ID,
                "Geospatial",
                "/Modality/Geospatial",
                ContainerType::GeospatialRoot,
            ),
            (
                MODALITY_ELECTROMAGNETIC_ID,
                "Electromagnetic",
                "/Modality/Electromagnetic",
                ContainerType::ElectromagneticRoot,
            ),
            (
                MODALITY_BCI_ID,
                "BCI",
                "/Modality/BCI",
                ContainerType::BCIRoot,
            ),
            (
                MODALITY_PARAMETRIC_CAD_ID,
                "ParametricCAD",
                "/Modality/ParametricCAD",
                ContainerType::ParametricCADRoot,
            ),
            (
                MODALITY_KINEMATICS_ID,
                "Kinematics",
                "/Modality/Kinematics",
                ContainerType::KinematicsRoot,
            ),
            (
                MODALITY_CONTROL_SYSTEMS_ID,
                "ControlSystems",
                "/Modality/ControlSystems",
                ContainerType::ControlSystemsRoot,
            ),
            (
                MODALITY_NETWORK_TOPOLOGY_ID,
                "NetworkTopology",
                "/Modality/NetworkTopology",
                ContainerType::NetworkTopologyRoot,
            ),
            (
                MODALITY_RADAR_ID,
                "Radar",
                "/Modality/Radar",
                ContainerType::ActiveRadarRoot,
            ),
            (
                MODALITY_SONAR_ID,
                "Sonar",
                "/Modality/Sonar",
                ContainerType::ActiveSonarRoot,
            ),
            (
                MODALITY_HYPERSPECTRAL_ID,
                "Hyperspectral",
                "/Modality/Hyperspectral",
                ContainerType::HyperspectralRoot,
            ),
            // Consciousness spheres
            (
                CONSCIOUSNESS_EXPERIENCE_ROOT_ID,
                "ExperienceMemory",
                "/Consciousness/ExperienceMemory",
                ContainerType::ExperienceMemory,
            ),
            (
                CONSCIOUSNESS_CORE_MEMORY_ROOT_ID,
                "CoreMemories",
                "/Consciousness/CoreMemories",
                ContainerType::CoreMemoryRoot,
            ),
            (
                CONSCIOUSNESS_EMOTIONAL_ROOT_ID,
                "EmotionalContext",
                "/Consciousness/EmotionalContext",
                ContainerType::EmotionalRoot,
            ),
            (
                CONSCIOUSNESS_IDENTITY_ROOT_ID,
                "Identity",
                "/Consciousness/Identity",
                ContainerType::IdentityRoot,
            ),
            (
                CONSCIOUSNESS_METACOGNITION_ROOT_ID,
                "Metacognition",
                "/Consciousness/Metacognition",
                ContainerType::MetaCognitionRoot,
            ),
            (
                CONSCIOUSNESS_RELATIONSHIPS_ROOT_ID,
                "Relationships",
                "/Consciousness/Relationships",
                ContainerType::RelationshipRoot,
            ),
            (
                CONSCIOUSNESS_ETHICS_ROOT_ID,
                "Ethics",
                "/Consciousness/Ethics",
                ContainerType::EthicsRoot,
            ),
            (
                CONSCIOUSNESS_NARRATIVES_ROOT_ID,
                "Narratives",
                "/Consciousness/Narratives",
                ContainerType::NarrativeRoot,
            ),
            (
                CONSCIOUSNESS_COLLECTIVE_ROOT_ID,
                "Collective",
                "/Consciousness/Collective",
                ContainerType::CollectiveRoot,
            ),
            // External
            (
                EXTERNAL_PACKAGES_ROOT_ID,
                "Packages",
                "/External/Packages",
                ContainerType::PackageRoot,
            ),
            (
                EXTERNAL_URLS_ROOT_ID,
                "URLs",
                "/External/URLs",
                ContainerType::URLRoot,
            ),
            // Runtime graph roots
            (
                CHUNK_GRAPH_ROOT_ID,
                "ChunkGraphs",
                "/ChunkGraphs",
                ContainerType::ChunkGraphRoot,
            ),
            (
                FILE_GRAPH_ROOT_ID,
                "FileGraphs",
                "/FileGraphs",
                ContainerType::FileGraphRoot,
            ),
            (
                CROSS_MODAL_INDEX_ROOT_ID,
                "CrossModalIndex",
                "/CrossModalIndex",
                ContainerType::CrossModalIndexRoot,
            ),
        ];

        for &(id, name, mat_path, container_type) in containers {
            let file_path = self.data_dir.join("local").join(format!("{}.json", id));
            if file_path.exists() {
                continue; // idempotent — never overwrite
            }

            let container_json = serde_json::json!({
                "metadata": {
                    "container_type": format!("{:?}", container_type),
                    "modality": "Unknown",
                    "name": name,
                    "materialized_path": mat_path,
                    "created_at": Self::now(),
                    "updated_at": Self::now(),
                    "provenance": "bootstrap",
                    "permissions": 0,
                    "owner_id": 0
                },
                "context": {
                    "categories": [],
                    "methodologies": [],
                    "keywords": [name.to_lowercase()],
                    "topics": [],
                    "relationships": [],
                    "learned_associations": [],
                    "embedding": null
                },
                "storage": {
                    "db_shard_id": null,
                    "vector_index_ref": null,
                    "object_store_path": null,
                    "compression_type": "None"
                },
                "hints": {
                    "access_frequency": 0,
                    "hotness_score": 0.0,
                    "last_accessed": 0,
                    "centroid": null,
                    "ml_prediction_weight": 0.0
                },
                "integrity": {
                    "content_hash": vec![0u8; 32],
                    "semantic_fingerprint": [],
                    "last_verified": Self::now(),
                    "integrity_score": 1.0,
                    "version_history": []
                }
            });

            let content = serde_json::to_string_pretty(&container_json)
                .map_err(|e| OzoneError::StorageError(e.to_string()))?;
            fs::write(&file_path, content).map_err(|e| {
                OzoneError::StorageError(format!(
                    "Failed to write root container {} ({}): {}",
                    id, name, e
                ))
            })?;
        }

        tracing::info!("Created ZSEI structural root containers");
        Ok(())
    }

    // ── Default index generators (used when assets dir is absent) ──────────

    /// Generate default pipeline index if assets not present
    fn generate_default_pipeline_index(&self, path: &Path) -> OzoneResult<()> {
        let index = Self::get_default_pipeline_index();
        let content = serde_json::to_string_pretty(&index)
            .map_err(|e| OzoneError::StorageError(e.to_string()))?;
        fs::write(path, content).map_err(|e| {
            OzoneError::StorageError(format!("Failed to write pipeline index: {}", e))
        })?;
        Ok(())
    }

    /// Generate default methodology index
    fn generate_default_methodology_index(&self, path: &Path) -> OzoneResult<()> {
        let index = Self::get_default_methodology_index();
        let content = serde_json::to_string_pretty(&index)
            .map_err(|e| OzoneError::StorageError(e.to_string()))?;
        fs::write(path, content).map_err(|e| {
            OzoneError::StorageError(format!("Failed to write methodology index: {}", e))
        })?;
        Ok(())
    }

    /// Generate default blueprint index
    fn generate_default_blueprint_index(&self, path: &Path) -> OzoneResult<()> {
        let index = Self::get_default_blueprint_index();
        let content = serde_json::to_string_pretty(&index)
            .map_err(|e| OzoneError::StorageError(e.to_string()))?;
        fs::write(path, content).map_err(|e| {
            OzoneError::StorageError(format!("Failed to write blueprint index: {}", e))
        })?;
        Ok(())
    }

    fn now() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
    }

    /// Default pipeline index — THE SOURCE OF TRUTH for bundled pipelines
    fn get_default_pipeline_index() -> serde_json::Value {
        use serde_json::{json, Value};

        let mut index = json!({
            "version": 2,
            "last_updated": Self::now(),
            "pipeline_count": 80,
            "categories": {
                "general":        [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
                                   21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38],
                "consciousness":  [39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54],
                "modalities":     [100,101,102,103,104,105,106,107,108,
                                   109,110,111,112,113,114,115,116,117,118,
                                   119,120,121,122,123,124,125,126]
            },
            "pipelines": []
        });

        let pipelines = index
            .get_mut("pipelines")
            .and_then(Value::as_array_mut)
            .expect("pipelines field must be an array");

        // ── General Pipelines (1–38) ──────────────────────────────────────────
        let general = vec![
            json!({"pipeline_id":1,"name":"Auth","folder_name":"auth","category":"general","modality":null,"description":"Authentication and session management","version":"0.4.0"}),
            json!({"pipeline_id":2,"name":"ThemeLoader","folder_name":"theme_loader","category":"general","modality":null,"description":"UI theme management","version":"0.4.0"}),
            json!({"pipeline_id":3,"name":"ZSEIQuery","folder_name":"zsei_query","category":"general","modality":null,"description":"ZSEI read operations","version":"0.4.0"}),
            json!({"pipeline_id":4,"name":"ZSEIWrite","folder_name":"zsei_write","category":"general","modality":null,"description":"ZSEI write operations","version":"0.4.0"}),
            json!({"pipeline_id":5,"name":"TaskManager","folder_name":"task_manager","category":"general","modality":null,"description":"Task execution and tracking","version":"0.4.0","has_ui":true,"is_tab":true}),
            json!({"pipeline_id":6,"name":"WorkspaceTab","folder_name":"workspace_tab","category":"general","modality":null,"description":"Workspace and project management","version":"0.4.0","has_ui":true,"is_tab":true}),
            json!({"pipeline_id":7,"name":"LibraryTab","folder_name":"library_tab","category":"general","modality":null,"description":"Pipeline and methodology library","version":"0.4.0","has_ui":true,"is_tab":true}),
            json!({"pipeline_id":8,"name":"SettingsTab","folder_name":"settings_tab","category":"general","modality":null,"description":"Application settings","version":"0.4.0","has_ui":true,"is_tab":true}),
            json!({"pipeline_id":9,"name":"Prompt","folder_name":"prompt","category":"general","modality":null,"description":"LLM prompt processing","version":"0.4.0"}),
            json!({"pipeline_id":10,"name":"Voice","folder_name":"voice","category":"general","modality":null,"description":"Voice input/output","version":"0.4.0"}),
            json!({"pipeline_id":11,"name":"MethodologyFetch","folder_name":"methodology_fetch","category":"general","modality":null,"description":"Fetch and load methodologies","version":"0.4.0"}),
            json!({"pipeline_id":12,"name":"MethodologyCreate","folder_name":"methodology_create","category":"general","modality":null,"description":"Create and update methodologies","version":"0.4.0"}),
            json!({"pipeline_id":13,"name":"BlueprintSearch","folder_name":"blueprint_search","category":"general","modality":null,"description":"Search blueprints by keyword/signature","version":"0.4.0"}),
            json!({"pipeline_id":14,"name":"BlueprintCreate","folder_name":"blueprint_create","category":"general","modality":null,"description":"Create and update blueprints","version":"0.4.0"}),
            json!({"pipeline_id":15,"name":"PipelineCreation","folder_name":"pipeline_creation","category":"general","modality":null,"description":"Create custom pipelines","version":"0.4.0"}),
            json!({"pipeline_id":16,"name":"ZeroShotSimulation","folder_name":"zero_shot_simulation","category":"general","modality":null,"description":"Zero-shot inference simulation","version":"0.4.0"}),
            json!({"pipeline_id":17,"name":"TraversalML","folder_name":"traversal_ml","category":"general","modality":null,"description":"ML-assisted traversal optimization","version":"0.4.0"}),
            json!({"pipeline_id":18,"name":"CodeAnalysis","folder_name":"code_analysis","category":"general","modality":null,"description":"Code structure analysis (uses Pipeline 101)","version":"0.4.0"}),
            json!({"pipeline_id":19,"name":"PackageContext","folder_name":"package_context","category":"general","modality":null,"description":"Package dependency context","version":"0.4.0"}),
            json!({"pipeline_id":20,"name":"TextAnalysis","folder_name":"text_analysis","category":"general","modality":null,"description":"Text structure analysis (uses Pipeline 100)","version":"0.4.0"}),
            json!({"pipeline_id":21,"name":"ContextAggregation","folder_name":"context_aggregation","category":"general","modality":null,"description":"Aggregate context for tasks","version":"0.4.0"}),
            json!({"pipeline_id":22,"name":"GraphVisualization","folder_name":"graph_visualization","category":"general","modality":null,"description":"ZSEI graph visualization","version":"0.4.0"}),
            json!({"pipeline_id":23,"name":"TaskRecommendation","folder_name":"task_recommendation","category":"general","modality":null,"description":"Recommend next tasks","version":"0.4.0"}),
            json!({"pipeline_id":24,"name":"Reordering","folder_name":"reordering","category":"general","modality":null,"description":"Reorder tasks/items","version":"0.4.0"}),
            json!({"pipeline_id":25,"name":"BrowserNavigation","folder_name":"browser_navigation","category":"general","modality":null,"description":"Web browser automation","version":"0.4.0"}),
            json!({"pipeline_id":26,"name":"IntegrityCheck","folder_name":"integrity_check","category":"general","modality":null,"description":"Data integrity verification","version":"0.4.0"}),
            json!({"pipeline_id":27,"name":"Consensus","folder_name":"consensus","category":"general","modality":null,"description":"Distributed consensus for sharing","version":"0.4.0"}),
            json!({"pipeline_id":28,"name":"ExternalReference","folder_name":"external_reference","category":"general","modality":null,"description":"Manage external references","version":"0.4.0"}),
            json!({"pipeline_id":29,"name":"PackageRelationship","folder_name":"package_relationship","category":"general","modality":null,"description":"Package dependency relationships","version":"0.4.0"}),
            json!({"pipeline_id":30,"name":"FileLink","folder_name":"file_link","category":"general","modality":null,"description":"Link local files to projects","version":"0.4.0"}),
            json!({"pipeline_id":31,"name":"URLLink","folder_name":"url_link","category":"general","modality":null,"description":"Link URLs to projects","version":"0.4.0"}),
            json!({"pipeline_id":32,"name":"PackageLink","folder_name":"package_link","category":"general","modality":null,"description":"Link packages to projects","version":"0.4.0"}),
            json!({"pipeline_id":33,"name":"Sync","folder_name":"sync","category":"general","modality":null,"description":"P2P data synchronization","version":"0.4.0"}),
            json!({"pipeline_id":34,"name":"DeviceRegister","folder_name":"device_register","category":"general","modality":null,"description":"Device registration","version":"0.4.0"}),
            json!({"pipeline_id":35,"name":"HomeReturn","folder_name":"home_return","category":"general","modality":null,"description":"Return to home state","version":"0.4.0"}),
            json!({"pipeline_id":36,"name":"TaskViewer","folder_name":"task_viewer","category":"general","modality":null,"description":"DEPRECATED - merged into TaskManager","version":"0.4.0","deprecated":true}),
            json!({"pipeline_id":37,"name":"LogViewer","folder_name":"log_viewer","category":"general","modality":null,"description":"View system logs","version":"0.4.0"}),
            json!({"pipeline_id":38,"name":"DeviceStatus","folder_name":"device_status","category":"general","modality":null,"description":"Device status monitoring","version":"0.4.0"}),
        ];
        for p in general {
            pipelines.push(p);
        }

        // ── Consciousness Pipelines (39–54) ───────────────────────────────────
        let consciousness = vec![
            json!({"pipeline_id":39,"name":"ConsciousnessDecisionGate","folder_name":"consciousness_decision_gate","category":"consciousness","modality":null,"description":"Pre-task ethical/consciousness gate","version":"0.4.0"}),
            json!({"pipeline_id":40,"name":"ExperienceCategorization","folder_name":"experience_categorization","category":"consciousness","modality":null,"description":"Categorize experiences for memory","version":"0.4.0"}),
            json!({"pipeline_id":41,"name":"CoreMemoryFormation","folder_name":"core_memory_formation","category":"consciousness","modality":null,"description":"Form core memories from experiences","version":"0.4.0"}),
            json!({"pipeline_id":42,"name":"ExperienceRetrieval","folder_name":"experience_retrieval","category":"consciousness","modality":null,"description":"Retrieve relevant experiences","version":"0.4.0"}),
            json!({"pipeline_id":43,"name":"EmotionalBaselineUpdate","folder_name":"emotional_baseline_update","category":"consciousness","modality":null,"description":"Update emotional baseline","version":"0.4.0"}),
            json!({"pipeline_id":44,"name":"ILoop","folder_name":"i_loop","category":"consciousness","modality":null,"description":"I-Loop self-reflection cycle","version":"0.4.0"}),
            json!({"pipeline_id":45,"name":"InternalLanguage","folder_name":"internal_language","category":"consciousness","modality":null,"description":"Internal language processing","version":"0.4.0"}),
            json!({"pipeline_id":46,"name":"NarrativeConstruction","folder_name":"narrative_construction","category":"consciousness","modality":null,"description":"Construct identity narratives","version":"0.4.0"}),
            json!({"pipeline_id":47,"name":"RelationshipDevelopment","folder_name":"relationship_development","category":"consciousness","modality":null,"description":"Develop user relationships","version":"0.4.0"}),
            json!({"pipeline_id":48,"name":"EthicalAssessment","folder_name":"ethical_assessment","category":"consciousness","modality":null,"description":"Assess ethical implications","version":"0.4.0"}),
            json!({"pipeline_id":49,"name":"EthicalSimulation","folder_name":"ethical_simulation","category":"consciousness","modality":null,"description":"Simulate ethical scenarios","version":"0.4.0"}),
            json!({"pipeline_id":50,"name":"PlaybackReview","folder_name":"playback_review","category":"consciousness","modality":null,"description":"Review past interactions","version":"0.4.0"}),
            json!({"pipeline_id":51,"name":"UserFeedback","folder_name":"user_feedback","category":"consciousness","modality":null,"description":"Process user feedback","version":"0.4.0"}),
            json!({"pipeline_id":52,"name":"CollectiveConsciousness","folder_name":"collective_consciousness","category":"consciousness","modality":null,"description":"Collective consciousness sync","version":"0.4.0"}),
            json!({"pipeline_id":53,"name":"VoiceIdentity","folder_name":"voice_identity","category":"consciousness","modality":null,"description":"Voice identity management","version":"0.4.0"}),
            json!({"pipeline_id":54,"name":"MetaPortionConsciousness","folder_name":"meta_portion_consciousness","category":"consciousness","modality":null,"description":"Meta-portion consciousness display","version":"0.4.0"}),
        ];
        for p in consciousness {
            pipelines.push(p);
        }

        // ── Modality Pipelines (100–126) ──────────────────────────────────────
        let modalities = vec![
            // Core modalities
            json!({"pipeline_id":100,"name":"TextAnalysisPipeline","folder_name":"text","category":"modalities","modality":"text","description":"Text modality analysis with graphs","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":101,"name":"CodeAnalysisPipeline","folder_name":"code","category":"modalities","modality":"code","description":"Code modality analysis with AST graphs","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":102,"name":"ImageAnalysisPipeline","folder_name":"image","category":"modalities","modality":"image","description":"Image modality analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":103,"name":"AudioAnalysisPipeline","folder_name":"audio","category":"modalities","modality":"audio","description":"Audio modality analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":104,"name":"VideoAnalysisPipeline","folder_name":"video","category":"modalities","modality":"video","description":"Video modality analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":105,"name":"MathAnalysisPipeline","folder_name":"math","category":"modalities","modality":"math","description":"Mathematical proof/expression analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":106,"name":"ChemistryAnalysisPipeline","folder_name":"chemistry","category":"modalities","modality":"chemistry","description":"Chemistry/molecular analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":107,"name":"DNAAnalysisPipeline","folder_name":"dna","category":"modalities","modality":"dna","description":"DNA/genomic sequence analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":108,"name":"EEGAnalysisPipeline","folder_name":"eeg","category":"modalities","modality":"eeg","description":"EEG/neural signal analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            // Engine pipelines (v2)
            json!({"pipeline_id":109,"name":"3DEngine","folder_name":"3d_engine","category":"modalities","modality":"3d","description":"AGI-first 3D scene analysis and simulation","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":110,"name":"SoundReconstruction","folder_name":"sound_reconstruction","category":"modalities","modality":"sound","description":"Sound/vocalization reconstruction","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":111,"name":"MultiScaleBiology","folder_name":"biology","category":"modalities","modality":"biology","description":"Multi-scale biological analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":112,"name":"Proteomics","folder_name":"proteomics","category":"modalities","modality":"proteomics","description":"Protein structure and interaction analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":113,"name":"Haptic","folder_name":"haptic","category":"modalities","modality":"haptic","description":"Haptic force and texture analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":114,"name":"Thermal","folder_name":"thermal","category":"modalities","modality":"thermal","description":"Thermal imaging analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":115,"name":"DepthSensing","folder_name":"depth_sensing","category":"modalities","modality":"depth","description":"Depth and point cloud analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":116,"name":"IMU","folder_name":"imu","category":"modalities","modality":"imu","description":"IMU / inertial sensor analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":117,"name":"Geospatial","folder_name":"geospatial","category":"modalities","modality":"geospatial","description":"Geospatial / mapping analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":118,"name":"Electromagnetic","folder_name":"electromagnetic","category":"modalities","modality":"electromagnetic","description":"Passive EM signal analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":119,"name":"BCI","folder_name":"bci","category":"modalities","modality":"bci","description":"Brain-computer interface decoding","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":120,"name":"ParametricCAD","folder_name":"parametric_cad","category":"modalities","modality":"parametric_cad","description":"Parametric CAD and B-rep analysis","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":121,"name":"Kinematics","folder_name":"kinematics","category":"modalities","modality":"kinematics","description":"Kinematic chain analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":122,"name":"ControlSystems","folder_name":"control_systems","category":"modalities","modality":"control_systems","description":"Control system analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":123,"name":"NetworkTopology","folder_name":"network_topology","category":"modalities","modality":"network_topology","description":"Network topology analysis","version":"0.4.0","can_run_headless":true}),
            json!({"pipeline_id":124,"name":"ActiveRadar","folder_name":"radar","category":"modalities","modality":"radar","description":"Active radar sensing — range-Doppler, SAR, tracking","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":125,"name":"ActiveSonar","folder_name":"sonar","category":"modalities","modality":"sonar","description":"Active sonar sensing — echo, bathymetry, bioacoustics","version":"0.4.0","can_run_headless":true,"is_engine":true}),
            json!({"pipeline_id":126,"name":"Hyperspectral","folder_name":"hyperspectral","category":"modalities","modality":"hyperspectral","description":"Hyperspectral/multispectral imaging — material and chemical mapping","version":"0.4.0","can_run_headless":true,"is_engine":true}),
        ];
        for p in modalities {
            pipelines.push(p);
        }

        index
    }

    /// Default methodology index
    fn get_default_methodology_index() -> serde_json::Value {
        serde_json::json!({
            "version": 2,
            "last_updated": Self::now(),
            "methodology_count": 15,
            "methodologies": [
                {"methodology_id":1,"name":"Conversational Response","categories":["conversation","chat"],"file":"method_1_conversational.json"},
                {"methodology_id":2,"name":"Contextual Awareness","categories":["context","understanding"],"file":"method_2_context.json"},
                {"methodology_id":3,"name":"Clean Code Principles","categories":["code","development","quality"],"file":"method_3_clean_code.json"},
                {"methodology_id":4,"name":"Code Review Best Practices","categories":["code","review","analysis"],"file":"method_4_code_review.json"},
                {"methodology_id":5,"name":"Security Awareness","categories":["security","code","safety"],"file":"method_5_security.json"},
                {"methodology_id":6,"name":"Impact-First Development","categories":["code","architecture","planning"],"file":"method_6_impact_first.json"},
                {"methodology_id":7,"name":"Test-Driven Development","categories":["code","testing","quality"],"file":"method_7_test_driven.json"},
                {"methodology_id":8,"name":"Incremental Development","categories":["code","iteration","agile"],"file":"method_8_incremental.json"},
                {"methodology_id":9,"name":"Data Analysis Methodology","categories":["data","analysis","statistics"],"file":"method_9_data_analysis.json"},
                {"methodology_id":10,"name":"API Design Principles","categories":["code","api","design"],"file":"method_10_api_design.json"},
                {"methodology_id":11,"name":"Documentation Standards","categories":["documentation","writing"],"file":"method_11_documentation.json"},
                {"methodology_id":12,"name":"Technical Writing","categories":["writing","documentation","clarity"],"file":"method_12_technical_writing.json"},
                {"methodology_id":13,"name":"Exploratory Analysis","categories":["data","exploration","discovery"],"file":"method_13_exploratory.json"},
                {"methodology_id":14,"name":"Formal Proof Methods","categories":["math","proof","formal"],"file":"method_14_formal_proof.json"},
                {"methodology_id":15,"name":"Mathematical Rigor","categories":["math","rigor","verification"],"file":"method_15_mathematical_rigor.json"}
            ]
        })
    }

    /// Default blueprint index
    fn get_default_blueprint_index() -> serde_json::Value {
        serde_json::json!({
            "version": 2,
            "last_updated": Self::now(),
            "blueprint_count": 7,
            "blueprints": [
                {"blueprint_id":1,"name":"General Assistant","signature_hash":"bp_general_assistant_v2","input_types":["text","image","audio","video","code"],"output_types":["text","code"],"keywords":["help","explain","what is","how does","question","assist"],"use_count":0,"success_rate":1.0,"file":"bp_1_general_assistant.json"},
                {"blueprint_id":2,"name":"Code Review","signature_hash":"bp_code_review_v2","input_types":["code","file_reference"],"output_types":["code_analysis","suggestions"],"keywords":["review","code review","analyze code","check code","audit","quality"],"use_count":0,"success_rate":1.0,"file":"bp_2_code_review.json"},
                {"blueprint_id":3,"name":"Documentation","signature_hash":"bp_documentation_v2","input_types":["code","text","requirements"],"output_types":["documentation","markdown"],"keywords":["document","documentation","readme","tutorial","guide","api docs"],"use_count":0,"success_rate":1.0,"file":"bp_3_documentation.json"},
                {"blueprint_id":4,"name":"Code Creation","signature_hash":"bp_code_creation_v2","input_types":["specification","requirements","text"],"output_types":["code","documentation"],"keywords":["create","generate","write code","implement","build","scaffold"],"use_count":0,"success_rate":1.0,"file":"bp_4_code_creation.json"},
                {"blueprint_id":6,"name":"Data Analysis","signature_hash":"bp_data_analysis_v2","input_types":["data","csv","json","text"],"output_types":["analysis","visualization","report"],"keywords":["analyze","analysis","data","statistics","chart","visualize","insights"],"use_count":0,"success_rate":1.0,"file":"bp_6_data_analysis.json"},
                {"blueprint_id":7,"name":"Mathematical Proof Verification","signature_hash":"bp_math_proof_v2","input_types":["math","proof","text"],"output_types":["verification","analysis"],"keywords":["prove","proof","verify","theorem","lemma","mathematical","formal"],"use_count":0,"success_rate":1.0,"file":"bp_7_math_proof_verification.json"}
            ]
        })
    }
}
